sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install scikit-learn

script:
    - python setup.py install
    - python examples/watermelon/main.py
    - python examples/iris/main.py

after_success:
    - codecov
